# yaml-language-server: $schema=../schema.json
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

tutorial: true

run:
  name: "all"
  prefix: "2022-FR"

  scenarios:
    enable: true
    file: "config/scen.2022+dmg_nucl.yaml"
  disable_progressbar: true
  shared_resources:
    policy: false

enable:
  build_cutout: false
  retrieve_cutout: true

scenario:
  clusters:
  - 5
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons: []

countries: ['FR']

electricity:

  extendable_carriers:
    Generator: [OCGT, solar, solar-hsat, onwind, offwind-ac, offwind-dc]
    StorageUnit: [battery]
    Store: [H2]
    Link: [H2 pipeline]

  renewable_carriers: [solar, solar-hsat, onwind, offwind-ac, offwind-dc]
  co2limit_enable: true
  co2limit: 0

  powerplants_filter: "(DateOut >= 2020 or DateOut != DateOut) and not (Country == 'Germany' and Fueltype == 'Nuclear')"
  transmission_limit: v1.0

data: # added section due to forked repo, see issue #2016 in repo
  cutout:
    source: build 
    version: unknown

atlite:
  default_cutout: europe-2022-era5_fg10_lmlt


renewable:
  offwind-ac:
    max_depth: false
  offwind-dc:
    max_depth: false
  offwind-float:
    max_depth: false
    min_depth: false

clustering:
  temporal:
    resolution_elec: False
    resolution_sector: 3h

solving:
  options:
    noisy_costs: false
    assign_all_duals: true
  check_objective:
    enable: false
    expected_value: 6.96e+08

plotting:
  map:
    boundaries:
  eu_node_location:
    x: -5.5
    y: 46.
  costs_max: 1000
  costs_threshold: 0.0000001
  energy_max:
  energy_min:
  energy_threshold: 0.000001